Client setup
AGH-Narzedzia-Informatyczne-2023-2024/kidang-tikus pull request #10
Opened 2023-11-09 21:21 UTC by jaanonim

Adding client part of game and editorconfig for project.

2023-11-09 23:33 UTC, jbanasik approved these changes
Looks good to me! :D

2023-11-10 21:15 UTC, kpustelnik requested changes
Please review suggestions - thx

2023-11-10 21:31 UTC, jaanonim commented on .editorconfig
No, this should be here. It's to assure that every editor is configured in the same way. You can read more [here](https://editorconfig.org/)

2023-11-10 21:34 UTC, jaanonim commented on client/main.py
> +screen = pygame.display.set_mode((1280, 720))
It's great idea. Maybe 1080x1920? What do you think? @kpustelnik

2023-11-10 21:35 UTC, jaanonim commented on client/main.py
> +    clock.tick(60)
Let's add it to the trello as task for later, we have for iportant stuff to do now.

2023-11-10 21:36 UTC, jaanonim commented on client/main.py
> +            running = False
I don't know. I copied it from docs :-)

2023-11-10 21:57 UTC, kpustelnik commented on client/main.py
> +screen = pygame.display.set_mode((1280, 720))
@jaanonim Did you mean 1920x1080? I don't have vertical monitor :(

2023-11-10 21:57 UTC, kpustelnik commented on client/main.py
> +            running = False
@jaanonim I see. I believe we can use it for now then.

2023-11-10 21:58 UTC, kpustelnik commented on client/main.py
> +    clock.tick(60)
Sounds good!

2023-11-10 21:59 UTC, jaanonim commented on client/main.py
> +screen = pygame.display.set_mode((1280, 720))
My bad, of course I meant 1920x1080.

2023-11-10 22:00 UTC, kpustelnik commented on .editorconfig
Wow that's helpful! Cool

2023-11-10 22:04 UTC, kpustelnik commented on client/main.py
> +screen = pygame.display.set_mode((1280, 720))
@jaanonim Let's change and I guess hte PR is ready then!

2023-11-10 22:12 UTC, jaanonim commented on client/main.py
> +screen = pygame.display.set_mode((1280, 720))
@kpustelnik please re-review

2023-11-10 22:15 UTC, kpustelnik approved these changes
That's awesome! Thx for PR!

2023-11-12 12:28 UTC, merged